### PR TITLE
Fix encrypt promise error

### PR DESCRIPTION
**Pull request by svipben**
- Updated README example
- Increased package version (patch)
- Fixed encrypt promise error (https://github.com/tectiv3/react-native-aes/issues/15)

### CODE REVIEW

**Comment by tectiv3** [comment]
That's a lot of unnecessary changes...
Let me play with it on the weekend.

**Comment by svipben** [comment]
What is unnecessary maybe only README update, but it's way readable now. Also, fixed some formatting issues to again increase readability. The issue was to replace `keyData.length` to the `kCCKeySizeAES128`.

It will be very cool if you will be able to merge it and release it, but it's up to you :)

**Comment by tectiv3** [comment]
yeah yeah, I totally plan to do it!

**Comment by tectiv3** [comment]
Hey, check out https://github.com/tectiv3/react-native-aes/commit/933ff76a95b5ba859e9e3d55d2f90304d1f51ed9 already published to npm as 1.3.0.

**Pull request closed without merging**
