### PR TITLE
Adding algorithm param to encrypt and decrypt method, defaulting to a…

### PR DESCRIPTION
**Pull request by iralution**
Adding algorithm param to encrypt and decrypt method, defaulting to a…

### CODE REVIEW

**Comment by tectiv3** [comment]
Okay, but it needs readme update, typescript definitions update and android of course :)

**Comment by iralution** [comment]
I agree with readme and typescript.. On android it works based on the keylength, as far as I could see, so the parameter would only be kinda "dummy"

**Comment by franzejr** [comment]
I think this can be merged, right ? I need to do AES128 and right now on iOS it doesn't change based on the key length....

**Comment by tectiv3** [comment]
Without support on android side (even if it is dummy) I can't merge it.

**Pull request merged**
